---
- hosts: all
  remote_user: e34
  become: yes
  become_method: sudo
  tasks:
#   - name: updates a server
#     apt: update_cache=yes

   - name: install git
     apt: name=git

   - name: install apt-transport-https
     apt: name=apt-transport-https

   - name: install ca-certificates
     apt: name=ca-certificates

   - name: install java8
     apt: name=openjdk-8-jdk state=latest install_recommends=no

   - name: add to docker dist
     shell: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

   - name: create file for docker
     file: path=/etc/apt/sources.list.d/docker.list state=touch

   - name: copy content to file
     copy: content="deb https://apt.dockerproject.org/repo ubuntu-wily main" dest="/etc/apt/sources.list.d/docker.list"

   - name: updates server
     apt: update_cache=yes

   - name: purge
     shell: sudo apt-get purge lxc-docker

   - name: verify apt
     shell: apt-cache policy docker-engine

   - name: install maven3
     apt: name=maven

   - name: download selenium
     get_url: url=http://goo.gl/IHP6Qw dest=/home/e34/Downloads/selenium-standalone.jar

   - name: clone git repo
     git: repo=https://github.com/palotas/seleniumtraining.git
          dest=/home/e34/Downloads/selenium

   - name: install docker
     apt: name=docker-engine

   - name: install pip
     apt: name=python-pip

   - name: install docker-py
     pip: name=docker-py


   - name: build the jenkins image from the Dockerfile
     docker_image: >
        name=e34-jenkins
        tag=v1
        path=/home/e34/docker
        state=present

   - name: stop jenkins docker container
     docker:
         name: e34-jenkins
         image: jenkins
         state: stopped



   - name: start jenkins docker container
     docker:
         name: e34-jenkins
         image: e34-jenkins:v1
         ports: "8080:8080"
         state: started


